version: '3.8'
name: go-backend

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  pg-data: