definitions:
  models.Post:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact:
    email: bogomolovs693@gmail.com
  description: This is my first Go API
  title: Golang API Example
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: Get details of all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Post'
            type: array
      summary: Get details of all posts
      tags:
      - posts
swagger: "2.0"
